on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Description' 
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
  
        
     

